version: "3.3"
services:
  api:
    build: ./myCircle-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOCKER_COMPOSE_ENABLED=True
    ports:
      - "5000:80"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
  sqlproxy:
    image: "gcr.io/cloudsql-docker/gce-proxy:1.10"
    ports: 
      - "3306:3306"
    volumes:
      - "$PWD:/config"
    command: ["/cloud_sql_proxy", "-instances=${SQLPROXY_INSTANCE_NAME}=tcp:0.0.0.0:3306", "-credential_file=/config/gcloud-sqlproxy-key.json"]
